name: CI DATE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print current time
        run: |
          current_date_time=$(date)
          echo "Current date and time: $current_date_time"
